[project]
name = "customer-feedback-analysis-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.39.9",
    "langchain-aws>=0.2.28",
    "langchain>=0.3.26",
    "langgraph>=0.5.3",
    "pydantic>=2.11.7",
    "icecream>=2.1.5",
]
